language: node_js
node_js:
- '8'
- '10'
notifications:
  email:
    on_success: never
    on_failure: always
script: yarn build
deploy:
  provider: npm
  email: npm@jupiterone.io
  api_key:
    secure: F6l43vPZ84+zx7C7IrJ4VeBcOsrSAWhDXzpHKFAVbBjW76H/AiWSllmDXQ/hQ5ViQFS03D1gmmstz1qXHAfV2RHnBb9osoMnckuDSA5nbfoOn8mW27dEV6ZvVuoYIEIX0Bn4xVskTGefGA5sJeirh6qpaxgPCGzi3auCj8GjLg5cTn12cNMmuyf5sZnB2gvvocXoD4wAU1mQUwnZd5Df194boZOnU431r9oneu8mil0C6yf3NI6jl8uvcVGtm8FeO4iE5NO3yQ99wpUA3pTHKLFwH3f5+CHmVX3FrkoOD19qZIDISqcz3qXY9YOBlgOFvAfBR0iXfDo8H55b7twpJFUhsctJzmcCVoP2Qa77wrawOOB8uagLNy4p9r0IbH7xFOsgM+VG4LYVE/US/OVaWfiCtPQ6XlDjY/thxNZ5bknk6/3evVxGX9ECX/g0uv0MwPiNPY6gJfJ1NKFvBvVSbMJhX5bSICcHQzXXpQt4qnguzVddYcKZEgBJ9A5WCz+AJzVymmxf2DJCP4nmkxCHCpZrnnYFnnjLOR5sqJ22+EtzaFro6tX5aey5IqLLZXWDfRd9GzYjM3IDUh7HDIticwV1ugWrOfa7zVtZtKsMZ68OID/YLp7yGlQzUHCFxQQCCEebsjvTJFcjL/HGBN1GB6cwnbkVM2QHlKzsOqCgTkk=
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: JupiterOne/graph-jumpcloud
    node: '8'
    